# Generated by Django 3.0.5 on 2021-10-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
