# Generated by Django 3.0.5 on 2021-10-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20211020_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.IntegerField()),
                ('borrower', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
