# Generated by Django 3.0.5 on 2021-10-20 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='lender',
        ),
        migrations.AddField(
            model_name='transaction',
            name='borrower_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='person.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='lender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='person.Person'),
            preserve_default=False,
        ),
    ]
