# Generated by Django 3.0.5 on 2021-10-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20211020_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='borrower_id',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='lender_id',
            new_name='lender',
        ),
    ]
